M48
; DRILL file {KiCad 9.0.7} date 2026-01-21T12:21:26+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-21T12:21:26+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X150.485Y-87.2
X156.265Y-87.2
T2
X128.925Y-93.4
X140.355Y-93.4
M30
